import type { ImageRoomDefinition } from './ImageRoomDefinition'

type CuratedRoomId = 'sports-center' | 'auditorium' | 'learning-lab'
const curatedRoom = (room: ImageRoomDefinition): ImageRoomDefinition => Object.freeze(room)

export const CURATED_CAMPUS_ROOMS: Readonly<Record<CuratedRoomId, ImageRoomDefinition>> = Object.freeze({
  'sports-center': curatedRoom({
    id: 'sports-center',
    title: 'TEDU Swimming Pool',
    spawnNodeId: 'entrance',
    image: {
      url: 'assets/rooms/tedu-swimming-pool-wide-r2.png',
      width: 1672,
      height: 941,
      sha256: 'de48f7ffef84dbd487cd4e2ac0596c10d6c5e31846baf2408a4a51ea82439660',
    },
    nodes: [
      { id: 'entrance', x: 50, y: 91, z: 0 },
      { id: 'dive-queue', x: 50, y: 83, z: 0 },
      { id: 'front-left', x: 27, y: 82, z: 0 },
      { id: 'front-right', x: 69, y: 82, z: 0 },
      { id: 'east-front', x: 78.2, y: 75.2, z: 0 },
      { id: 'east-mid', x: 91.2, y: 63.4, z: 0 },
      { id: 'east-back', x: 90.2, y: 38.7, z: 0 },
      { id: 'rear-right', x: 79, y: 35, z: 0 },
      { id: 'rear-center', x: 60, y: 29, z: 0 },
      { id: 'rear-left', x: 43.8, y: 24.2, z: 0 },
      { id: 'west-back', x: 31, y: 36, z: 0 },
      { id: 'west-mid', x: 20, y: 49, z: 0 },
      { id: 'west-front', x: 15, y: 66, z: 0 },
    ],
    edges: [
      { from: 'entrance', to: 'front-left', kind: 'walk' },
      { from: 'entrance', to: 'front-right', kind: 'walk' },
      { from: 'entrance', to: 'dive-queue', kind: 'walk' },
      { from: 'front-left', to: 'west-front', kind: 'walk' },
      { from: 'west-front', to: 'west-mid', kind: 'walk' },
      { from: 'west-mid', to: 'west-back', kind: 'walk' },
      { from: 'west-back', to: 'rear-left', kind: 'walk' },
      { from: 'rear-left', to: 'rear-center', kind: 'walk' },
      { from: 'rear-center', to: 'rear-right', kind: 'walk' },
      { from: 'rear-right', to: 'east-back', kind: 'walk' },
      { from: 'east-back', to: 'east-mid', kind: 'walk' },
      { from: 'east-mid', to: 'east-front', kind: 'walk' },
      { from: 'east-front', to: 'front-right', kind: 'walk' },
    ],
    seats: [],
    occluders: [],
    actors: {},
  }),
  auditorium: curatedRoom({
    id: 'auditorium',
    title: 'Ahmet Ersan Auditorium',
    spawnNodeId: 'entrance',
    image: {
      url: 'assets/rooms/tedu-ahmet-ersan-auditorium-diagonal-r2.png',
      width: 1672,
      height: 941,
      sha256: '7783287e9b07ab72fd5500aa028436f1b5c7b6e6c5ef98888fa40e7938b7ce72',
    },
    nodes: [
      { id: 'entrance', x: 49, y: 83, z: 0 },
      { id: 'lower-aisle', x: 61, y: 79, z: 0 },
      { id: 'lower-row', x: 59, y: 70.5, z: 0 },
      { id: 'lower-left-aisle', x: 38, y: 70, z: 0 },
      { id: 'middle-aisle', x: 67, y: 68, z: 0 },
      { id: 'middle-row', x: 71, y: 58, z: 0 },
      { id: 'middle-left-aisle', x: 58, y: 65, z: 0 },
      { id: 'upper-aisle', x: 76, y: 44, z: 0 },
      { id: 'upper-row', x: 77, y: 42, z: 0 },
      { id: 'upper-left-aisle', x: 47, y: 43, z: 0 },
      { id: 'rear-aisle', x: 93, y: 44, z: 0 },
      { id: 'stage-steps', x: 22, y: 51, z: 0 },
      { id: 'stage', x: 25, y: 42, z: 1 },
    ],
    edges: [
      { from: 'entrance', to: 'lower-aisle', kind: 'walk' },
      { from: 'entrance', to: 'lower-left-aisle', kind: 'walk' },
      { from: 'lower-aisle', to: 'lower-row', kind: 'walk' },
      { from: 'lower-aisle', to: 'lower-left-aisle', kind: 'walk' },
      { from: 'lower-aisle', to: 'middle-aisle', kind: 'walk' },
      { from: 'lower-left-aisle', to: 'middle-left-aisle', kind: 'walk' },
      { from: 'middle-aisle', to: 'middle-row', kind: 'walk' },
      { from: 'middle-aisle', to: 'middle-left-aisle', kind: 'walk' },
      { from: 'middle-aisle', to: 'upper-aisle', kind: 'walk' },
      { from: 'middle-left-aisle', to: 'upper-left-aisle', kind: 'walk' },
      { from: 'upper-aisle', to: 'upper-row', kind: 'walk' },
      { from: 'upper-aisle', to: 'upper-left-aisle', kind: 'walk' },
      { from: 'upper-aisle', to: 'rear-aisle', kind: 'walk' },
      { from: 'upper-left-aisle', to: 'rear-aisle', kind: 'walk' },
      { from: 'lower-aisle', to: 'stage-steps', kind: 'walk' },
      { from: 'stage-steps', to: 'stage', kind: 'stair' },
    ],
    seats: [
      { id: 'auditorium-lower', label: 'Lower row', approachNodeId: 'lower-row', sit: { x: 61.5, y: 67, z: 0 }, facing: 'nw', foregroundMask: [{ x: 60.35, y: 64.3 }, { x: 62.65, y: 64.8 }, { x: 63.7, y: 66.2 }, { x: 63.3, y: 68.2 }, { x: 61.1, y: 68.8 }, { x: 60.2, y: 67.2 }], occlusion: null, foregroundAsset: null },
      { id: 'auditorium-middle', label: 'Middle row', approachNodeId: 'middle-row', sit: { x: 74, y: 55, z: 0 }, facing: 'nw', foregroundMask: [{ x: 72.8, y: 52.5 }, { x: 74.8, y: 52.2 }, { x: 75.5, y: 53.6 }, { x: 75.2, y: 56 }, { x: 73.5, y: 56.5 }, { x: 72.7, y: 55.2 }], occlusion: null, foregroundAsset: null },
      { id: 'auditorium-upper', label: 'Upper row', approachNodeId: 'upper-row', sit: { x: 80, y: 40, z: 0 }, facing: 'nw', foregroundMask: [{ x: 79.2, y: 38.3 }, { x: 80.9, y: 38.1 }, { x: 81.6, y: 39.3 }, { x: 81.4, y: 41.4 }, { x: 79.9, y: 41.7 }, { x: 79.1, y: 40.7 }], occlusion: null, foregroundAsset: null },
    ],
    occluders: [],
    actors: {},
  }),
  'learning-lab': curatedRoom({
    id: 'learning-lab',
    title: 'TEDU Computer Lab',
    spawnNodeId: 'entrance',
    image: {
    url: 'assets/rooms/tedu-computer-lab-wide-r4-small-computers.png',
      width: 1672,
      height: 941,
      sha256: '2b6c33d42727b9ae580d35bbf38595c7e4af72c783cb360e4a71f0c2342abbff',
    },
    nodes: [
      { id: 'entrance', x: 10, y: 78, z: 0 },
      { id: 'front-left', x: 25, y: 86, z: 0 },
      { id: 'front-right', x: 78, y: 82, z: 0 },
      { id: 'round-rug', x: 91, y: 68, z: 0 },
      { id: 'center-floor', x: 66, y: 90, z: 0 },
      { id: 'window-aisle', x: 25.282296650717704, y: 72.37619553666313, z: 0 },
      { id: 'blue-cushion', x: 34.880382775119614, y: 82.8134962805526, z: 0 },
      { id: 'gray-cushion', x: 58.55502392344497, y: 69.1009564293305, z: 0 },
      { id: 'right-cushion', x: 76.19617224880383, y: 73.25079702444208, z: 0 },
      { id: 'back-aisle', x: 84, y: 46, z: 0 },
      { id: 'activity-table', x: 47.23923444976076, y: 91.82571732199789, z: 0 },
      { id: 'center-aisle', x: 45, y: 61, z: 0 },
      { id: 'rear-aisle', x: 65, y: 38, z: 0 },
      { id: 'left-rear-aisle', x: 25, y: 51, z: 0 },
    ],
    edges: [
      { from: 'entrance', to: 'window-aisle', kind: 'walk' },
      { from: 'entrance', to: 'front-left', kind: 'walk' },
      { from: 'front-left', to: 'blue-cushion', kind: 'walk' },
      { from: 'front-left', to: 'center-floor', kind: 'walk' },
      { from: 'center-floor', to: 'activity-table', kind: 'walk' },
      { from: 'center-floor', to: 'front-right', kind: 'walk' },
      { from: 'front-right', to: 'right-cushion', kind: 'walk' },
      { from: 'front-right', to: 'round-rug', kind: 'walk' },
      { from: 'round-rug', to: 'back-aisle', kind: 'walk' },
      { from: 'back-aisle', to: 'rear-aisle', kind: 'walk' },
      { from: 'rear-aisle', to: 'left-rear-aisle', kind: 'walk' },
      { from: 'left-rear-aisle', to: 'window-aisle', kind: 'walk' },
      { from: 'window-aisle', to: 'center-aisle', kind: 'walk' },
      { from: 'center-aisle', to: 'gray-cushion', kind: 'walk' },
      { from: 'gray-cushion', to: 'center-floor', kind: 'walk' },
    ],
    seats: [
      { id: 'window-chair', label: 'Left row computer chair', approachNodeId: 'window-aisle', sit: { x: 26, y: 66, z: 0 }, facing: 'ne', foregroundMask: [{ x: 23, y: 63 }, { x: 29, y: 60 }, { x: 30, y: 68 }, { x: 25, y: 70 }], occlusion: null, foregroundAsset: null },
      { id: 'blue-floor-cushion', label: 'Front-left computer chair', approachNodeId: 'blue-cushion', sit: { x: 35, y: 77.5, z: 0 }, facing: 'ne', foregroundMask: [{ x: 32, y: 74 }, { x: 38, y: 71 }, { x: 39, y: 80 }, { x: 34, y: 82 }], occlusion: null, foregroundAsset: null },
      { id: 'gray-floor-cushion', label: 'Centre computer chair', approachNodeId: 'gray-cushion', sit: { x: 57, y: 64, z: 0 }, facing: 'ne', foregroundMask: [{ x: 54, y: 61 }, { x: 60, y: 58 }, { x: 61, y: 67 }, { x: 56, y: 69 }], occlusion: null, foregroundAsset: null },
      { id: 'right-floor-cushion', label: 'Right row computer chair', approachNodeId: 'right-cushion', sit: { x: 75, y: 69, z: 0 }, facing: 'ne', foregroundMask: [{ x: 72, y: 66 }, { x: 78, y: 63 }, { x: 80, y: 72 }, { x: 75, y: 74 }], occlusion: null, foregroundAsset: null },
      { id: 'activity-table-seat', label: 'Front computer chair', approachNodeId: 'activity-table', sit: { x: 47, y: 88, z: 0 }, facing: 'ne', foregroundMask: [{ x: 44, y: 85 }, { x: 50, y: 82 }, { x: 52, y: 92 }, { x: 47, y: 95 }], occlusion: null, foregroundAsset: null },
    ],
    occluders: [],
    actors: {},
  }),
})
